// Shared adapter utilities — subprocess execution, file hashing, generated detection

export interface ExecResult {
  stdout: string;
  stderr: string;
  exitCode: number;
}

export async function exec(
  cmd: string[],
  opts?: { cwd?: string; env?: Record<string, string>; timeoutMs?: number },
): Promise<ExecResult> {
  const proc = Bun.spawn(cmd, {
    cwd: opts?.cwd,
    env: opts?.env ? { ...process.env, ...opts.env } : undefined,
    stdout: "pipe",
    stderr: "pipe",
  });

  if (opts?.timeoutMs) {
    const timeout = opts.timeoutMs;
    setTimeout(() => {
      try { proc.kill(); } catch {}
    }, timeout);
  }

  const [stdout, stderr, exitCode] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
    proc.exited,
  ]);
  return { stdout: stdout.trim(), stderr: stderr.trim(), exitCode };
}

export async function whichTool(name: string): Promise<string | null> {
  try {
    const result = await exec(["which", name]);
    return result.exitCode === 0 ? result.stdout : null;
  } catch {
    return null;
  }
}

export async function hashFile(path: string): Promise<string> {
  const file = Bun.file(path);
  const buf = await file.arrayBuffer();
  const hasher = new Bun.CryptoHasher("sha256");
  hasher.update(buf);
  return `sha256:${hasher.digest("hex")}`;
}

const GENERATED_MARKERS = [
  "// Code generated",
  "# Code generated",
  "// <auto-generated",
  "// auto-generated",
  "# This file is automatically @generated",
  "# Automatically generated",
  "@generated",
];

export async function isGenerated(path: string): Promise<boolean> {
  const file = Bun.file(path);
  const stream = file.stream();
  const reader = stream.getReader();
  try {
    const { value } = await reader.read();
    if (!value) return false;
    const head = new TextDecoder().decode(value.slice(0, 1024));
    return GENERATED_MARKERS.some((m) => head.includes(m));
  } finally {
    reader.releaseLock();
  }
}

export function hashSig(input: string): string {
  const hasher = new Bun.CryptoHasher("sha256");
  hasher.update(input);
  return hasher.digest("hex").slice(0, 8);
}

/**
 * Collect source files from a directory matching given extensions.
 * Returns relative paths from repoRoot.
 */
export async function collectFiles(
  dir: string,
  extensions: string[],
  repoRoot: string,
): Promise<string[]> {
  const { join, relative } = await import("node:path");
  const { readdir, stat } = await import("node:fs/promises");
  const results: string[] = [];

  async function walk(currentDir: string): Promise<void> {
    let entries;
    try {
      entries = await readdir(currentDir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      const fullPath = join(currentDir, entry.name);
      if (entry.isDirectory()) {
        // Skip common non-source directories
        if (
          entry.name === "node_modules" ||
          entry.name === ".git" ||
          entry.name === "target" ||
          entry.name === "bin" ||
          entry.name === "obj" ||
          entry.name === "__pycache__" ||
          entry.name === ".venv" ||
          entry.name === "venv" ||
          entry.name === "dist" ||
          entry.name === "build" ||
          entry.name === "cache"
        ) {
          continue;
        }
        await walk(fullPath);
      } else if (extensions.some((ext) => entry.name.endsWith(ext))) {
        results.push(relative(repoRoot, fullPath));
      }
    }
  }

  await walk(dir);
  return results;
}

/**
 * Detect circular dependencies using DFS.
 * Language-agnostic version that replaces unit prefixes in messages.
 */
export function detectCyclicDeps(
  deps: Array<{ from_unit_id: string; to_unit_id: string; kind: string }>,
  unitPrefix: string,
): Array<{
  file_id: string;
  position: { line: number; column: number };
  severity: "warning";
  message: string;
  tool: string;
}> {
  const adj = new Map<string, string[]>();
  for (const dep of deps) {
    const existing = adj.get(dep.from_unit_id);
    if (existing) {
      existing.push(dep.to_unit_id);
    } else {
      adj.set(dep.from_unit_id, [dep.to_unit_id]);
    }
  }

  const diagnostics: Array<{
    file_id: string;
    position: { line: number; column: number };
    severity: "warning";
    message: string;
    tool: string;
  }> = [];
  const visited = new Set<string>();
  const inStack = new Set<string>();
  const reportedCycles = new Set<string>();

  function dfs(node: string, path: string[]): void {
    if (inStack.has(node)) {
      const cycleStart = path.indexOf(node);
      if (cycleStart === -1) return;
      const cycle = path.slice(cycleStart);
      cycle.push(node);
      const cycleKey = [...cycle].sort().join(" -> ");
      if (reportedCycles.has(cycleKey)) return;
      reportedCycles.add(cycleKey);
      diagnostics.push({
        file_id: cycle[0]!,
        position: { line: 0, column: 0 },
        severity: "warning",
        message: `circular dependency detected: ${cycle.map((u) => u.replace(new RegExp(`^${unitPrefix}`), "")).join(" -> ")}`,
        tool: "cycle_detector",
      });
      return;
    }
    if (visited.has(node)) return;

    visited.add(node);
    inStack.add(node);
    path.push(node);

    for (const neighbor of adj.get(node) ?? []) {
      dfs(neighbor, path);
    }

    path.pop();
    inStack.delete(node);
  }

  for (const node of adj.keys()) {
    dfs(node, []);
  }

  return diagnostics;
}
