// <auto-generated>
// This file was generated by a tool. Do not edit manually.
// </auto-generated>
namespace TestProject.Services;

public class GeneratedHelper
{
    public static string AutoMethod() => "generated";
}
