// Code generated by protoc-gen-ts. DO NOT EDIT.

export interface GeneratedMessage {
  id: number;
  content: string;
}

export function createMessage(id: number, content: string): GeneratedMessage {
  return { id, content };
}
